export enum systemConstants {
    SYSTEM_OK = "ok",
    SYSTEM_LOADING = "loading",
    SYSTEM_ERROR = "error",
    SYSTEM_MODAL_SUBMIT = "SYSTEM_MODAL_SUBMIT",
    SYSTEM_MODAL_HIDE = "SYSTEM_MODAL_HIDE",
    SYSTEM_MODAL_ERROR = "SYSTEM_MODAL_ERROR",
    DELETE_ENTRY = "MODAL_DELETE_ENTRY",
}